services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
    # volumes:
    #   - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic-network
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.7.1
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elastic-network

volumes:
  elasticsearch-data:

networks:
  elastic-network:
    driver: bridge
