services:
  devtalk.api:
    image: fareselsadek/devtalk
    container_name: devtalkapp
    build:
      context: .
      dockerfile: src/DevTalk.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - postgres
      - redis  
    networks:
      - devtalk-network
    hostname: devtalk
    env_file:
      - .env
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devtalk-network
    hostname: devtalk-db
    env_file:
      - .env
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - devtalk-network  
    hostname: devtalk-redis
    command: ["redis-server", "--appendonly", "yes"]  
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:  

networks:
  devtalk-network:
    driver: bridge 