# This is a generated file. Not intended for manual editing.
services:
  devtalk.api:
    build:
      context: "C:\\Users\\fares\\source\\repos\\DevTalk"
      dockerfile: "src/DevTalk.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/DevTalk.API.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net9.0/DevTalk.API.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "fareselsadek/devtalk:dev"
    ports: []
    volumes:
    - "C:\\Users\\fares\\source\\repos\\DevTalk\\src\\DevTalk.API:/app:rw"
    - "C:\\Users\\fares\\source\\repos\\DevTalk:/src:rw"
    - "C:\\Users\\fares\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
