name: DevTalk-CD-Production
on:
  push:
    branches:
    - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.2.0
        with:
          dotnet-version: 9.0.x
      - name: restore dependenceis
        run: dotnet restore DevTalk.sln
      - name: Build
        run: dotnet build DevTalk.sln --no-restore -c release
      - name: publish
        run: dotnet publish ./src/DevTalk.API/DevTalk.API.csproj -o ${{ env.DOTNET_ROOT }}/api --no-build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: api-artifact
          path: ${{env.DOTNET_ROOT}}/api
  deploy:
    environment: 
      name: 'Production'
      url: 'https://api.devtalk.me'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./src/DevTalk.API/Dockerfile
        push: true
        tags: fareselsadek/devtalk:v2

    - name: Deploy to Azure VM via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          sudo -i
          docker-compose pull
          sudo systemctl restart docker-compose-app
